### ISSUE TITLE
"No component found with scheme" when using components such as camel-metrics, camel-ftp, etc. in Karaf

### ISSUE THREAD

**Issue by garyhodgson** [astefanutti/camel-cdi#10] opened 2015-05-14 18:04 UTC
Hi,

I'm attempting to use camel-cdi with camel 2.15.2 on Karaf 3.0.3, and I'm having a couple of issues.  

I got everything working with a simple route and the default context, but as I want to spread by route definitions across bundles I then tried using the ContextName annotation.  This threw a [NullPointerException](https://gist.github.com/garyhodgson/c514de3f819313fad531#file-npestacktrace-txt) which is due to ```extension.getContextInfo(name)``` returning null in CdiCamelContext.postConstruct.  A bit of debugging seems to show that although the namedContexts list in CdiCamelExtension is correctly populated via camelContextNames, when getContextInfo is called namedContexts is empty.  I'm not sure exactly why.

As a workaround I switched to the latest code and put in a null check in CdiCamelContext. This got me to the stage where I can deploy multiple bundles each containing its own context and routes.  However, when I define a route which uses a  component other than "simple" it throws an [exception](https://gist.github.com/garyhodgson/c514de3f819313fad531#file-nocomponentstacktrace-txt) due to "No component found with scheme".  So far I have tried ftp, rest and metrics, all with the same outcome.  (I should note that I ensured that the relevant feature was installed, e.g. camel-metrics.)

At first I thought it might be a karaf start-level problem but so far changing the start levels does not seem to have an impact.  I am about to delve into the code myself but wanted to post this issue in case it's something you may be aware of. Have you perhaps had success creating routes, other than simple examples, in a karaf instance?

**Comment by garyhodgson** [comment] 2015-05-24 11:48
I believe I have produced some kind of fix for this issue.  It allows the use of camel components registered as OSGi services, but I suspect there may be a better way of doing the same thing.  The work so far can be found in this commit: 441928bfc7b73da9046bcbd1eda1756dcd20cb50

At first I attempted to have CdiCamelContext extend OsgiDefaultCamelContext, but had difficulty making the BundleContext available for the OsgiDefaultCamelContext constructor.  I then tried replicating its functionality which so far involves wrapping CdiCamelRegistry using OsgiCamelContextHelper.wrapRegistry, and setting the component resolver to OsgiComponentResolver.  

This only happens if there is a bundle context available.  It might be prefereable though to have a distinct OsgiCdiCamelContext (which either extends CdiCamelContext, or reimplements the logic) so the OSGi specific stuff doesn't pollute CdiCamelContext.  One could also argue that a OsgiCdiCamelContext should go in its own artifact, e.g. camel-cdi-osgi, so that the required dependencies also don't pollute the camel-cdi artifact.

Worth noting is that the above commit includes a workaround for the other bug mentioned in issue #10, whereby if the contextinfo for a custom context name is not found then the CdiEventNotifier is registered regardless.  (The real fix will be to work out why the namedContexts map is not populated when called in the postConstruct of CdiCamelContext.)

As I'm pretty new to CDI and OSGi I am of course open to suggestions on how this would be better implemented the "CDI way".

**Comment by garyhodgson** [comment] 2015-05-24 11:55
One thing I forgot to mention.  I don't think the fix is complete as there is some functionality that still doesn't work.  When using the (metrics component)[http://camel.apache.org/metrics-component.html] the metrics defined as routes appear to work fine, but I am unable to turn on metrics for all routes via ```context.addRoutePolicyFactory(new MetricsRoutePolicyFactory());```.  I suspect there is a mismatch between CDI and OSGi which causes the policy to not trigger.

**Comment by scsynergy** [comment] 2015-05-26 06:43
The issue you describe in your last comment sort of reminds me of the one I had found with hawtio:
https://github.com/hawtio/hawtio/issues/1915
The issue was really caused by the JAXB version, not by Camel or Hawtio. Might this be the case with your issue, too?

**Comment by garyhodgson** [comment] 2015-05-26 06:49
Thanks for the suggestion @scsynergy - i'll take a look once I get home.

**Comment by astefanutti** [comment] 2015-05-31 16:40
Hi Gary,

Sorry for the late reply and thanks for the thorough analysis.

Having one CDI container started per bundle logically leads to the behavior that you face and confirms your approach of using OSGi services is correct.

I'm cc'ing @cmoulliard that may shed some light on this as he's done more advanced tests with Karaf than the integration tests located in the `karaf` module, which do not cover your use cases.

In the meantime, I'll work ASAP on this to work the best approach out to alleviate the coupling with OSGi related classes as you've pointed out. I'll then update the integration tests to cover these use cases.

**Comment by garyhodgson** [comment] 2015-06-04 21:06
Just a heads-up: I updated my branch with b0db384 which adds an OSGi DataFormatResolver and TypeConverter, as otherwise the Property Injection had issues.

**Comment by astefanutti** [comment] 2015-12-15 18:07
@garyhodgson I've just completed the initial development for the OSGi integration that should bring CDI on par with Spring for the Camel OSGi support.

I've created a Camel Metrics CDI sample that should cover your test cases: https://github.com/astefanutti/camel-cdi/tree/cc3f15f68513eabaa6c0312caa6bd469bd56e477/samples/metrics/src/main/java/org/apache/camel/cdi/sample/metrics

And have it successfully running in Karaf: https://github.com/astefanutti/camel-cdi/blob/cc3f15f68513eabaa6c0312caa6bd469bd56e477/envs/osgi/src/test/java/org/apache/camel/cdi/osgi/MetricsPaxExamTest.java#L107

I'm closing this issue though feel free to raise new ones.

**Closed** 2015-12-15 18:07 UTC
Labels: OSGi
